language: go
go:
  - 1.14

branches:
  only:
  - master

jobs:
  include:
    - stage: test
      script:
        - echo "test begin"
        - go mod verify
        - go test
        - echo "test end"
    - stage: release
      script:
        - echo "try release"
