language: go
go:
  - 1.14

branches:
  only:
  - master

install:
  - curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o ~/semantic-release && chmod +x ~/semantic-release
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr

# jobs:
#   include:
#     - stage: test
#       script:
#         - go test

script:
  - sh ./.travis/release.sh

notifications:
  email: false
